name: NuclearFactions-crates2
version: 1.0.0
api: [3.0.0-ALPHA6, 3.0.0]
main: SourSmirnoff\SourCrates\Main
author: SourSmirnoff
commands:
    cratekey:
        usage: "/cratekeyvote <player>"
        description: Gives a player a crate key
        permission: cratekeyvote.give
permissions:
    cratekeyvote:
        default: op
        description: "Allows the player to use all of the CrateKey commands"
        children:
            cratekeyvote.give:
                default: op
                description: "Allows the player to give another player a CrateKey"
